#!/bin/bash

source ../.shared/utils.sh
initkata "$CONTENTS"

mkdir -p src/main/java/exercise
touch src/main/java/exercise/App.java

echo '/*
 * This Java source file was generated by the Gradle init task.
 */
package exercise;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
'>> src/main/java/exercise/App.java

cp ../../.shared/pre-existing/applying-plugins.gradle build.gradle
